config/routes.rb
SampleApp::Application.routes.draw do
	resources :users

	match '/contact', :to => 'pages#contact'
	match '/about', :to => 'pages#about'
	match '/help', :to => 'pages#help'
	match '/signup', :to => 'users#new'

	root :to => 'pages#home'

end

app/models/user.rb
# == Schema Information
# Schema version: 20110131165359
#
# Table name: users
#
#  id         :integer(4)      not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
	attr_accessor :password
	attr_accessible :name, :email, :password, :password_confirmation

	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :name, :presence => true,
									:length => { :maximum => 50 }
	validates :email, :presence => true,
									:format => { :with => email_regex },
									:uniqueness => { :case_sensitive => false } 
	validates :password, :presence => true,
											:confirmation => true,
											:length => { :within => 6..40 }

	before_save :encrypt_password
	
	def has_password? (submitted_password)
	end
	
	private

		def encrypt_password
			self.encrypted_password = encrypt(password)
		end

		def encrypt(string)
			string 
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
		@title = "Home"
  end

  def contact
		@title = "Contact"
  end

  def about 
		@title = "About"
  end

  def help 
		@title = "Help"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def show
		@user = User.find(params[:id])
		@title = @user.name
	end

  def new
		@title = "Sign Up"
		@user = User.new(params[:user])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def title
	base_title = "Ruby on Rails Sample App"
	if @title.nil?
		base_title
		else
			"#{base_title} | #{@title}"
		end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
		
	def gravatar_for(user, options = { :size => 50 })
		gravatar_image_tag(user.email.downcase, :alt => user.name,
																						:class => 'gravatar',
																						:gravatar => options)
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tutorial | <%= @title %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
	%head
		%title 
			= @title 
		= javascript_include_tag :defaults 
		= stylesheet_link_tag 'screen', :media => 'screen' 
		= stylesheet_link_tag 'reset', :media => 'screen' 

		= csrf_meta_tag
	%body
		.main_container
			.header	
				= image_tag 'logo.png', :class => 'round'
			.navigation{:class => 'round'}
				%ul
					%li= link_to "Home", root_path
					%li= link_to "Help", help_path
					%li= link_to "Sign-In", #
			.clear
			.content{:class => 'round'}
				= yield 
			= render :partial => 'shared/footer'
			= debug(params) if Rails.env.developement?

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/contact.html.haml
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.haml
%h2
	Help
%p
	Get help on Ruby on Rails Tutorial at the
	%a{:href => "http://www.railstutorial.org/help"}
		Rails Tutorial help page.

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/home.html.haml
.interior_content
	%h2
		Sample App
	%p
		Find me in app/views/pages/home.html.erb

	= link_to "Sign up now!", '/signup', :class => "signup_button round" 

app/views/shared/_footer.html.haml
.footer{:class => 'round'} 
	%ul 
		%li= link_to "About", about_path  
		%li= link_to "Contact", contact_path 
		%li= link_to "News", # 

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/new.html.haml
.interior_content
	%h2
		Sign Up
	.signup_form
		= form_for(@user) do |f|
			.field
				= f.label :name
				= f.text_field :name
			.field
				= f.label :email
				= f.text_field :email
			.field
				= f.label :password
				= f.password_field :password
			.actions
				= f.submit "Sign Up"
	.clear

app/views/users/show.html.haml
.interior_content
	%h2
		= gravatar_for @user
		= @user.name

	.user_sidebar.round
		%h3 Name:
		%p= @user.name
		.clear	
		%h3 URL:
		%p= link_to user_path(@user), @user
.clear